[package]
name = "tqt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bech32 = "0.11.0"
curve25519-dalek = "4.1.3"
sha2 = "0.10.9"
ssh-key = { version = "0.6.7", features = ["ed25519"] }
ed25519-dalek = "2.1.1"
